version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: hilyzhzu
      POSTGRES_PASSWORD: NtjkigpnzWagFllkfI3-xZreXjPoCrSH
      POSTGRES_DB: hilyzhzu
    ports:
      - "5432:5432"
